name: Deploy as latest
on:
  workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.ref_name }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@7
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Setup Git user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Deploy version with mike
        run: |
          git pull
          mike deploy $BRANCH_NAME latest --push --update-aliases
